---
region: 'eu-west-2'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"
  - "eu-west-2c"

component: 'test'
deployment_identifier: "%{hiera('seed')}"

tags:
  ImportantTag: "important-value"

vpc_cidr: "10.1.0.0/16"

cluster_name: 'test-cluster'

number_of_broker_nodes: 2

kafka_version: "2.8.1"

s3_logs_enabled: false
s3_logs_bucket_name: ""
s3_logs_prefix: ""

include_default_ingress_rule: "yes"
include_default_egress_rule: "yes"

allowed_cidrs:
  - '10.1.0.0/16'
egress_cidrs:
  - '10.1.0.0/16'

private_zone_id: 'Z0211739BXR21FNN139O'
